---
title: "Risk of Associated Disease According to BMI and Waist Size"
author: "Nazrul"
date: "22 March 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

This Risk of Associated Disease According to BMI and Waist Size application was built for the Coursera Developing Data Products as part of the Data Science Specialization.

The shiny application developed for this assignment is available at:
https://ir-nazrul.shinyapps.io/riskdisease/

The source codes of ui.R and server.R available on GitHub repo at:
https://github.com/Ir-Nazrul/Developing_Data_Product

## What is Body Mass Index (BMI)?

BMI can be said as a screening tool which serves the purpose of identifying weight problems that possibly happen to adults, people over 18 years old.

It only helps to calculate the possibility of weight problems, nothing more nothing less.

The index will show that you are underweight, normal weight, overweight, or obesity.

BMI is calculated by dividing weight by the square of height as follows:

BMI = Weight (kg)/Height (m)2

## Waist circumference and disease risk

Waist circumference thresholds which indicate increased risk of disease are below:

* For women: risk is increased at more than or equal to 80 cm risk is high at more than or equal to 88 cm.

* For men: risk is increased at more than or equal to 94 cm risk is high at more than or equal to 102 cm for men.

## The Shiny Application

This application had divided into sidebar panel and main panel.

### Sidebar panel: 
* Numeric input - Height (cm) and Weight (kg)
* Slider - Waist size/circumference (inch)
* Radio button - Male or Female

### Main panel:
* Current measures
* Calculated BMI
* BMI category/classification
* Risk level of associated disease